# Numpy Checkpoint:

## Question 1:

In [5]:
import numpy as np 
a=np.array([[1,2,3],[4,5,6]])
new=a.tolist()
print(new)
type(new)

[[1, 2, 3], [4, 5, 6]]


list

## Question 2 :

### méthode 1: 

In [21]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
diag=np.diagonal(a)
somme=sum(diag)
print(somme)


15


### méthode 2: 

In [22]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
s=np.trace(a)
print(s)

15


## Question 3:

In [25]:
a=np.array([[1,2],[3,5]])
x=int(input())
print(a[a>x])

2
[3 5]


## Question 4: 

In [40]:
a=np.random.randint(2, 10, size=(5,5))
b=np.random.randint(2, 10, size=(5,5))
c=a+b
print(c)

[[ 5 13 10 10 16]
 [ 9 10 12 12  8]
 [12 12  7 12 17]
 [16 14 16 16 17]
 [13 13  4 10 11]]


## Question 5:

In [41]:
a=np.random.randint(2, 10, size=(5,5))
c=a - a.mean(axis=1,keepdims=True)
print(c)

[[ 1.  -2.   2.  -2.   1. ]
 [ 2.2 -0.8  1.2 -2.8  0.2]
 [-1.2  2.8 -2.2  0.8 -0.2]
 [ 2.   2.  -1.  -4.   1. ]
 [ 1.8 -0.2  2.8 -1.2 -3.2]]
